### ISSUE TITLE
Add post-training verification

### ISSUE THREAD

**Issue by daanelson** [replicate/cog-safe-push#16]
I'd like to add the ability to run a prediction on a trained model and validate that the model has actually learned what we want it to. 

Good to verify that a trainer not only runs but also trains effectively. 

Design would probably be something like : 

```
train:
  destination: <generated prediction model, e.g. andreasjansson/test-predict. leave
    blank to append '-dest' to the test model>
  destination_hardware: <hardware for the created prediction model, e.g. cpu>
  test_cases:
  - exact_string: <exact string match>
    inputs:
      <input1>: <value1>
```
